version: "3.9"
services:
  postgres:
    image: postgres:12.9
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products
    ports:
      - '55432:5432'